import type { Metadata } from 'next'
import './globals.css'
import '@radix-ui/themes/styles.css'
import { Inter as FontSans } from 'next/font/google'

import { Theme } from '@radix-ui/themes'

import { cn } from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <Theme>
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased',
            fontSans.variable,
          )}
        >
          {children}
        </body>
      </Theme>
    </html>
  )
}
